name: ChainDEVOPS CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Récupérer le code
        uses: actions/checkout@v4

      - name: 2. Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 3. Lint Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run lint

      - name: 4. Lint Backend
        working-directory: backend
        run: |
          npm ci
          npm run lint

      - name: 5. Test Backend
        working-directory: backend
        run: |
          npm ci
          npm test

      # --- SECTION FRONTEND ---
      - name: 3. Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chaindevops-frontend:latest -f docker/frontend.Dockerfile .

      # --- SECTION BACKEND ---
      - name: 4. Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chaindevops-backend:latest -f docker/backend.Dockerfile .

      # --- QUALITÉ ET SÉCURITÉ ---
      - name: 5. Analyser avec SonarCloud
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=MahdiGH10_ChainDEVOPS \
            -Dsonar.organization=mahdigh10 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.sources=backend,frontend/src
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 6. Scan de sécurité Trivy (Backend)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/chaindevops-backend:latest'
          format: 'table'
          exit-code: '0' 
          severity: 'CRITICAL,HIGH'

      # --- DEPLOIEMENT (PUSH) ---
      - name: 7. Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 8. Push des images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chaindevops-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chaindevops-backend:latest