name: ChainDEVOPS CI Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend && npm install
          cd ../backend && npm install

      - name: Run Lint (Phase 5.5)
        run: |
          cd frontend && npm run lint || echo "Lint terminé"

      - name: Run Tests (Phase 5.5)
        run: |
          cd backend && npm test || echo "Pas de tests définis"

      # --- ANALYSE QUALITÉ ---
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # --- BUILD LOCAL (Pour que Trivy puisse scanner sans erreur) ---
      - name: Build local images
        run: |
          docker build -t chaindevops-backend:test -f docker/backend.Dockerfile .
          docker build -t chaindevops-frontend:test -f docker/frontend.Dockerfile .

      # --- SÉCURITÉ DEVSECOPS (Scan des images locales) ---
      - name: Scan Backend (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'chaindevops-backend:test'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Scan Frontend (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'chaindevops-frontend:test'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      # --- AUTHENTIFICATION & PUSH FINAL ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Backend Image
        run: |
          docker tag chaindevops-backend:test ${{ secrets.DOCKERHUB_USERNAME }}/chaindevops-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chaindevops-backend:latest

      - name: Push Frontend Image
        run: |
          docker tag chaindevops-frontend:test ${{ secrets.DOCKERHUB_USERNAME }}/chaindevops-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chaindevops-frontend:latest